name: Build C++23

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install GCC 14
      run: |
        sudo apt update
        sudo apt install -y g++-14
        g++-14 --version
    
    - name: Build with GCC 14
      run: |
        cd src
        g++-14 -std=c++23 *.cpp -o stuff -lstdc++exp
        ./stuff
